/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * IT Platform
 * OpenAPI spec version: 0.0.1
 */
import { BASE_API_URL } from '@/app/constants/baseUrl'

export type PostNewAssetBody = {
  serialNumber: string
  name: string
  type: string
  /** @nullable */
  assignedTo: string | null
  datePurchased: string
  assetNumber: string
  createdBy: string
}

export type PostNewAsset201 = {
  success: boolean
  message: string
  /** @nullable */
  staff: string | null
}

export type PostNewAsset500 = {
  success: boolean
  message: string
  /** @nullable */
  staff: string | null
}

export type PostNewStaffBody = {
  name: string
  email: string
  department: string
  jobTitle: string
  createdBy: string
}

export type PostNewStaff201 = {
  success: boolean
  message: string
  staff: string
}

export type PostNewStaff500 = {
  success: boolean
  message: string
  /** @nullable */
  staff: string | null
}

export type GetAllStaffParams = {
  id?: string
}

export type GetAllStaff200ItemChangeLogItem = {
  updatedBy: string
  updatedAt: string
  updatedField: string
  previousValue: string
  newValue: string
}

export type GetAllStaff200Item = {
  id: string
  name: string
  email: string
  department: string
  jobTitle: string
  status: string
  /** @nullable */
  note: string | null
  assetHistoryList: string[]
  createdAt: string
  createdBy: string
  changeLog: GetAllStaff200ItemChangeLogItem[]
}

export type GetAllAssetsParams = {
  id?: string
}

export type GetAllAssets200ItemChangeLogItem = {
  updatedBy: string
  updatedAt: string
  updatedField: string
  /** @nullable */
  previousValue: string | null
  /** @nullable */
  newValue: string | null
}

export type GetAllAssets200Item = {
  id: string
  serialNumber: string
  name: string
  type: string
  /** @nullable */
  assignedTo: string | null
  /** @nullable */
  dateAssigned: string | null
  datePurchased: string
  assetNumber: string
  status: string
  /** @nullable */
  note: string | null
  createdAt: string
  createdBy: string
  changeLog: GetAllAssets200ItemChangeLogItem[]
}

export type DeleteAssetByIdBody = {
  updatedBy: string
}

export type DeleteAssetById200 = {
  success: boolean
  message: string
}

export type DeleteAssetById400 = {
  success: boolean
  message: string
}

export type DeleteAssetById500 = {
  success: boolean
  message: string
}

export type PostAssetToStaffEmailBody = {
  assetId: string
  updatedBy: string
  userConfirmed?: boolean
}

export type PostAssetToStaffEmail200 = {
  success: boolean
  message: string
}

export type PostAssetToStaffEmail500 = {
  success: boolean
  message: string
}

export type PatchAssetDetailsIdBody = {
  status: string
  /** @nullable */
  note: string | null
  updatedBy: string
}

export type PatchAssetDetailsId200 = {
  success: boolean
  message: string
}

export type PatchAssetDetailsId500 = {
  success: boolean
  message: string
}

export type PatchStaffDetailsIdBody = {
  status: string
  /** @nullable */
  note: string | null
  updatedBy: string
}

export type PatchStaffDetailsId200 = {
  success: boolean
  message: string
}

export type PatchStaffDetailsId500 = {
  success: boolean
  message: string
}

export type GetAssetBySerialParams = {
  serialNumber: string
}

export type GetAssetBySerial200AssetListItem = {
  id: string
  serialNumber: string
  name: string
  type: string
  /** @nullable */
  assignedTo: string | null
  datePurchased: string
  assetNumber: string
  status: string
  /** @nullable */
  note: string | null
  createdAt: string
  createdBy: string
}

export type GetAssetBySerial200 = {
  success: boolean
  message: string
  assetList: GetAssetBySerial200AssetListItem[]
}

export type GetAssetByStaffEmailParams = {
  email: string
}

export type GetAssetByStaffEmail200AssetListItem = {
  id: string
  serialNumber: string
  name: string
  /** @nullable */
  email: string | null
}

export type GetAssetByStaffEmail200 = {
  success: boolean
  message: string
  assetList: GetAssetByStaffEmail200AssetListItem[]
}

export type GetAssetByStaffEmail500AssetListItem = {
  id: string
  serialNumber: string
  name: string
  /** @nullable */
  email: string | null
}

export type GetAssetByStaffEmail500 = {
  success: boolean
  message: string
  assetList: GetAssetByStaffEmail500AssetListItem[]
}

export const getPostNewAssetUrl = () => {
  return `${BASE_API_URL}/newAsset`
}

export const postNewAsset = async (
  postNewAssetBody: PostNewAssetBody,
  options?: RequestInit
): Promise<PostNewAsset201> => {
  const res = await fetch(getPostNewAssetUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postNewAssetBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostNewAsset201 = body ? JSON.parse(body) : {}

  return data
}

export const getPostNewStaffUrl = () => {
  return `${BASE_API_URL}/newStaff`
}

export const postNewStaff = async (
  postNewStaffBody: PostNewStaffBody,
  options?: RequestInit
): Promise<PostNewStaff201> => {
  const res = await fetch(getPostNewStaffUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postNewStaffBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostNewStaff201 = body ? JSON.parse(body) : {}

  return data
}

export const getGetAllStaffUrl = (params?: GetAllStaffParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${BASE_API_URL}/allStaff?${stringifiedParams}`
    : `${BASE_API_URL}/allStaff`
}

export const getAllStaff = async (
  params?: GetAllStaffParams,
  options?: RequestInit
): Promise<GetAllStaff200Item[]> => {
  const res = await fetch(getGetAllStaffUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetAllStaff200Item[] = body ? JSON.parse(body) : {}

  return data
}

export const getGetAllAssetsUrl = (params?: GetAllAssetsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${BASE_API_URL}/allAssets?${stringifiedParams}`
    : `${BASE_API_URL}/allAssets`
}

export const getAllAssets = async (
  params?: GetAllAssetsParams,
  options?: RequestInit
): Promise<GetAllAssets200Item[]> => {
  const res = await fetch(getGetAllAssetsUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetAllAssets200Item[] = body ? JSON.parse(body) : {}

  return data
}

export const getDeleteAssetByIdUrl = (id: string) => {
  return `${BASE_API_URL}/assetBy/${id}`
}

export const deleteAssetById = async (
  id: string,
  deleteAssetByIdBody: DeleteAssetByIdBody,
  options?: RequestInit
): Promise<DeleteAssetById200> => {
  const res = await fetch(getDeleteAssetByIdUrl(id), {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteAssetByIdBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: DeleteAssetById200 = body ? JSON.parse(body) : {}

  return data
}

export const getPostAssetToStaffEmailUrl = (email: string) => {
  return `${BASE_API_URL}/assetToStaff/${email}`
}

export const postAssetToStaffEmail = async (
  email: string,
  postAssetToStaffEmailBody: PostAssetToStaffEmailBody,
  options?: RequestInit
): Promise<PostAssetToStaffEmail200> => {
  const res = await fetch(getPostAssetToStaffEmailUrl(email), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAssetToStaffEmailBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostAssetToStaffEmail200 = body ? JSON.parse(body) : {}

  return data
}

export const getPatchAssetDetailsIdUrl = (id: string) => {
  return `${BASE_API_URL}/assetDetails/${id}`
}

export const patchAssetDetailsId = async (
  id: string,
  patchAssetDetailsIdBody: PatchAssetDetailsIdBody,
  options?: RequestInit
): Promise<PatchAssetDetailsId200> => {
  const res = await fetch(getPatchAssetDetailsIdUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchAssetDetailsIdBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PatchAssetDetailsId200 = body ? JSON.parse(body) : {}

  return data
}

export const getPatchStaffDetailsIdUrl = (id: string) => {
  return `${BASE_API_URL}/staffDetails/${id}`
}

export const patchStaffDetailsId = async (
  id: string,
  patchStaffDetailsIdBody: PatchStaffDetailsIdBody,
  options?: RequestInit
): Promise<PatchStaffDetailsId200> => {
  const res = await fetch(getPatchStaffDetailsIdUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchStaffDetailsIdBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PatchStaffDetailsId200 = body ? JSON.parse(body) : {}

  return data
}

export const getGetAssetBySerialUrl = (params: GetAssetBySerialParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${BASE_API_URL}/assetBySerial?${stringifiedParams}`
    : `${BASE_API_URL}/assetBySerial`
}

export const getAssetBySerial = async (
  params: GetAssetBySerialParams,
  options?: RequestInit
): Promise<GetAssetBySerial200> => {
  const res = await fetch(getGetAssetBySerialUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetAssetBySerial200 = body ? JSON.parse(body) : {}

  return data
}

export const getGetAssetByStaffEmailUrl = (
  params: GetAssetByStaffEmailParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${BASE_API_URL}/assetByStaffEmail?${stringifiedParams}`
    : `${BASE_API_URL}/assetByStaffEmail`
}

export const getAssetByStaffEmail = async (
  params: GetAssetByStaffEmailParams,
  options?: RequestInit
): Promise<GetAssetByStaffEmail200> => {
  const res = await fetch(getGetAssetByStaffEmailUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetAssetByStaffEmail200 = body ? JSON.parse(body) : {}

  return data
}
